fix(test-utils, modules-sdk, utils, medusa): fix plugin:add for monorepo projects (#16308)
yalc doesn't natively support monorepos. So, `medusa plugin:add` adds the dependency incorrectly to the project and running the project fails with errors like:

```
error:   Cannot find module '@medusajs/commerce-mcp-plugin/.medusa/server/src/modules/mcp'
```

The fix is to:

1. In `plugin:add`, resolve the installation directory (for monorepos, it's the root. for standalone, it's the directory that medusa is executed from)
2. Run the install command of the package manager after adding the plugin with yalc, since it only writes it in the current project's directory. For monorepos, it should be added in the root instead.
3. In all loaders that load plugin resources, ensure the plugin and its resources and dependencies is loaded correctly relative to the Medusa project (which didn't work properly in monorepos, causing the error above)