fix(build): attempt fix TS error with medusa-core-utils
Error: medusa-core-utils:build: src/create-require-from-path.ts(16,34):
 error TS2339: Property 'createRequireFromPath' does not exist on type
 typeof Module'.